version: '3.8'

services:
  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:postgresql://postgres:5432/PATIENT_TRIALS
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=P@ssw0rd1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL Database (for local development only)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=PATIENT_TRIALS
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=P@ssw0rd1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d PATIENT_TRIALS"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: