# Default configuration
spring:
  application:
    name: patient-trials-microservice
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

# Add actuator endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true

---
# Development environment profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/PATIENT_TRIALS}
    username: ${POSTGRES_USER:dev_user}
    password: ${POSTGRES_PASSWORD:P@ssw0rd1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    create-schemas: true
    schemas: flyway_history_schema, dbo
    locations: classpath:db/migration/postgresql

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.tajorgensen: DEBUG
    org.springframework.web: DEBUG

---
# Production environment profile (for Render deployment)
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  flyway:
    enabled: true
    create-schemas: true
    schemas: flyway_history_schema, dbo
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Production logging
logging:
  level:
    root: INFO
    com.tajorgensen: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"