spring:
  application:
    name: patient-trials

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  flyway:
    enabled: true
    create-schemas: true
    schemas: flyway_history_schema, dbo
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true

# Server configuration
server:
  port: 8080

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging configuration
logging:
  level:
    root: INFO
    com.sportskpi: DEBUG
    org.springframework.web: INFO
    #    org.hibernate: ERROR
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

---
# JUnit environment profile
spring:
  config:
    activate:
      on-profile: junit

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: dev_user
    password: P@ssw0rd1234
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    create-schemas: true
    schemas: flyway_history_schema, dbo
    locations: classpath:db/migration/h2

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop

    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

---
# Development environment profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/PATIENT_TRIALS
    username: dev_user
    password: P@ssw0rd1234
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    create-schemas: true
    schemas: flyway_history_schema, dbo
    locations: classpath:db/migration/postgresql

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
# Production environment profile (for Vercel deployment)
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: postgres://postgres.zwxcykphzbudngbguydn:qoMTxJvJN5LPkBkV@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    create-schemas: true
    schemas: flyway_history_schema, dbo
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect