-- Seed data for Patient Trial database (PostgreSQL version) --

-- PATIENT seed data
INSERT INTO dbo.PATIENT (NAME, DATE_OF_BIRTH, GENDER, MEDICAL_HISTORY, CREATED_AT, UPDATED_AT)
VALUES ('John Smith', '1980-05-15', 'M', 'Hypertension, Type 2 Diabetes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Sarah Johnson', '1975-08-21', 'F', 'Asthma', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Michael Brown', '1990-03-10', 'M', 'None', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Emily Davis', '1988-11-30', 'F', 'Migraine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Robert Wilson', '1965-04-25', 'M', 'Coronary Artery Disease, Hyperlipidemia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jennifer Martinez', '1982-09-12', 'F', 'Rheumatoid Arthritis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('David Thompson', '1972-07-08', 'M', 'GERD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jessica White', '1995-01-18', 'F', 'None', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Christopher Lee', '1978-06-22', 'M', 'Depression, Anxiety', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Amanda Garcia', '1992-12-05', 'F', 'Hypothyroidism', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Daniel Rodriguez', '1969-10-14', 'M', 'Type 1 Diabetes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Elizabeth Hernandez', '1985-02-27', 'F', 'Fibromyalgia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Matthew Lopez', '1973-03-19', 'M', 'Mild Asthma, Seasonal Allergies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Stephanie Scott', '1989-08-11', 'F', 'Polycystic Ovary Syndrome', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Andrew Mitchell', '1977-05-29', 'M', 'Hypertension', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Nicole Turner', '1993-04-16', 'F', 'None', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Thomas Parker', '1970-11-24', 'M', 'Osteoarthritis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Rebecca Adams', '1986-07-31', 'F', 'Migraines, Depression', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Kevin Campbell', '1974-09-09', 'M', 'High Cholesterol', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Laura Evans', '1991-01-08', 'F', 'Irritable Bowel Syndrome', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- DRUG seed data
INSERT INTO dbo.DRUG (NAME, CHEMICAL_FORMULA, MANUFACTURER, CREATED_AT, UPDATED_AT)
VALUES ('Metformin', 'C4H11N5', 'Novartis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lisinopril', 'C21H31N3O5', 'Merck', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Albuterol', 'C13H21NO2', 'GlaxoSmithKline', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Simvastatin', 'C25H38O5', 'Pfizer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Omeprazole', 'C17H19N3O3S', 'AstraZeneca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Levothyroxine', 'C15H11I4NO4', 'Abbott', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Amlodipine', 'C20H25ClN2O5', 'Bayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Sertraline', 'C17H17Cl2N', 'Teva', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Gabapentin', 'C9H17NO2', 'Sandoz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Ibuprofen', 'C13H18O2', 'Johnson & Johnson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Atorvastatin', 'C33H35FN2O5', 'Pfizer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Fluoxetine', 'C17H18F3NO', 'Eli Lilly', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Losartan', 'C22H23ClN6O', 'Merck', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Azithromycin', 'C38H72N2O12', 'Pfizer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Prednisone', 'C21H26O5', 'Novartis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- TRIAL seed data
INSERT INTO dbo.TRIAL (NAME, START_DATE, END_DATE, PROTOCOL_DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES ('Diabetes Prevention Study', '2024-01-10', '2025-07-10',
        'Double-blind RCT testing efficacy of new oral antidiabetic agent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Hypertension Management Trial', '2024-03-15', '2025-09-15',
        'Comparative effectiveness of combination therapy vs. monotherapy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Asthma Control Program', '2024-02-20', '2026-02-20', 'Long-term efficacy study of bronchodilator combinations',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cholesterol Reduction Initiative', '2024-04-05', '2025-10-05',
        'Evaluation of novel statin therapy at varying dosages', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Arthritis Pain Management', '2024-05-12', '2026-05-12',
        'Assessment of new anti-inflammatory for rheumatoid arthritis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Depression Treatment Comparison', '2024-01-25', '2025-07-25',
        'Comparing efficacy of SSRI vs new peptide-based therapy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Fibromyalgia Symptom Relief', '2024-06-08', '2026-06-08',
        'Testing combination therapy approach for pain management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('GERD Treatment Optimization', '2024-03-30', '2025-09-30',
        'Evaluating PPI dosing schedules for symptom management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- PATIENT_TRIAL seed data
INSERT INTO dbo.PATIENT_TRIAL (PATIENT_ID, TRIAL_ID, ENROLLMENT_DATE, TREATMENT_STATUS, CREATED_AT, UPDATED_AT)
VALUES (1, 1, '2024-01-15', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 1, '2024-01-17', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (11, 1, '2024-01-20', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (15, 1, '2024-01-22', 'WITHDRAWN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       (1, 2, '2024-03-18', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 2, '2024-03-20', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (15, 2, '2024-03-22', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (19, 2, '2024-03-25', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       (2, 3, '2024-02-25', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 3, '2024-02-27', 'WITHDRAWN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (13, 3, '2024-03-01', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       (5, 4, '2024-04-10', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (11, 4, '2024-04-12', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (15, 4, '2024-04-15', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (19, 4, '2024-04-18', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       (6, 5, '2024-05-15', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (12, 5, '2024-05-18', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (17, 5, '2024-05-20', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (18, 5, '2024-05-22', 'WITHDRAWN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       (9, 6, '2024-01-30', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (18, 6, '2024-02-02', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       (6, 7, '2024-06-10', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (12, 7, '2024-06-12', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (18, 7, '2024-06-15', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       (7, 8, '2024-04-05', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (10, 8, '2024-04-08', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (20, 8, '2024-04-10', 'WITHDRAWN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- PATIENT_TRIAL_DRUG seed data
INSERT INTO dbo.PATIENT_TRIAL_DRUG (PATIENT_TRIAL_ID, DRUG_ID, DOSAGE, DOSAGE_MEASUREMENT_TYPE, CREATED_AT, UPDATED_AT)
VALUES
    -- Diabetes Trial Drugs
    (1, 1, 500, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 11, 10, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 1, 1000, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 1, 750, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 1, 500, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Hypertension Trial Drugs
    (5, 2, 10, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 7, 5, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 2, 20, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 7, 5, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 2, 10, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 13, 50, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Asthma Trial Drugs
    (9, 3, 100, 'MICROGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 3, 100, 'MICROGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11, 3, 200, 'MICROGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Cholesterol Trial Drugs
    (12, 4, 20, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 4, 40, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 11, 10, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (15, 11, 20, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Arthritis Trial Drugs
    (16, 10, 800, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (16, 15, 10, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (17, 10, 600, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (17, 15, 5, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (18, 10, 800, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (19, 10, 600, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Depression Trial Drugs
    (20, 8, 50, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21, 12, 20, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Fibromyalgia Trial Drugs
    (22, 9, 300, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22, 12, 10, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23, 9, 600, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (24, 9, 300, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (24, 8, 25, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- GERD Trial Drugs
    (25, 5, 20, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (26, 5, 40, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (27, 5, 20, 'MILLIGRAMS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ADVERSE_EVENT seed data
INSERT INTO dbo.ADVERSE_EVENT (PATIENT_ID, TRIAL_ID, EVENT_DESCRIPTION, EVENT_SEVERITY, DATE_OF_OCCURRENCE, CREATED_AT,
                               UPDATED_AT)
VALUES (1, 1, 'Mild nausea', 'MILD', '2024-01-30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 1, 'Dizziness upon standing', 'MODERATE', '2024-02-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (15, 1, 'Severe gastrointestinal distress', 'SEVERE', '2024-02-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (15, 2, 'Dry cough', 'MILD', '2024-04-02', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 2, 'Ankle swelling', 'MODERATE', '2024-04-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (2, 3, 'Throat irritation', 'MILD', '2024-03-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (13, 3, 'Palpitations', 'MODERATE', '2024-03-22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 4, 'Muscle pain', 'MODERATE', '2024-05-03', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (19, 4, 'Memory issues', 'MILD', '2024-05-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (6, 5, 'Stomach pain', 'MODERATE', '2024-06-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (18, 5, 'Rash', 'SEVERE', '2024-06-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (9, 6, 'Insomnia', 'MODERATE', '2024-02-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (18, 6, 'Headache', 'MILD', '2024-02-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (12, 7, 'Drowsiness', 'MILD', '2024-06-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (18, 7, 'Dizziness', 'MODERATE', '2024-06-30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (7, 8, 'Constipation', 'MILD', '2024-04-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (20, 8, 'Severe abdominal pain', 'SEVERE', '2024-04-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);